name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build React frontend
        run: |
          cd client
          npm ci
          npm run build

      - name: Build Electron app
        run: |
          npm run dist

      - name: Rename artifacts
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          DIST_DIR=dist
          mkdir -p renamed_dist

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            for f in $DIST_DIR/*.exe; do
              mv "$f" "renamed_dist/FishingArtifact-win-$VERSION.exe"
            done
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            for f in $DIST_DIR/*.dmg $DIST_DIR/*.zip; do
              mv "$f" "renamed_dist/FishingArtifact-mac-$VERSION.${f##*.}"
            done
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            for f in $DIST_DIR/*.AppImage $DIST_DIR/*.deb; do
              mv "$f" "renamed_dist/FishingArtifact-linux-$VERSION.${f##*.}"
            done
          fi

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: "renamed_dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}